from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase


# Alembic autogenerate cannot produce stable constraint/index names without
# an explicit naming convention -- without this, every autogenerated
# migration risks inventing a new randomized constraint name for the same
# logical constraint.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Tüm ORM modelleri için ortak declarative base."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
